### ISSUE TITLE
Add ignore_older to OpenTraffic Log

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apigateway-openlogging-elk#188]
### Problem description

When starting the solution for the first time, Filebeat starts reading all available OpenTraffic-Event Log-Files. This may contain millions of requests, which might be useless, as they are perhaps even too old anyway. 
With that, it creates a lot of pressure, on a high volume environment.

See issue: #180 

### Feature request

The solution should read OpenTraffic Event Log-Files by default only up to a certain age using the ignore_older flag, as it's already configured for Trace-Files.

```yaml
- type: log
  paths: ["/var/log/opentraffic/*_traffic*.log"]
  close_inactive: 5m # Close filehandlers, if the file has not changed anymore
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
  fields_under_root: true
  # When initially started, don't try to read all existing OpenTraffic event logs
  ignore_older: "12h"
  fields:
    logtype: openlog
    gatewayName: ${GATEWAY_NAME:"API-Gateway"}
    gatewayRegion: ${GATEWAY_REGION:"N/A"}
    filebeatVersion: "2"
```
